version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "15:00"
      timezone: UTC
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
    labels:
      - ci/dependencies
    open-pull-requests-limit: 5
